# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .service_deployment import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "k8s-servicedeployment",
  "mod": "index",
  "fqn": "pulumi_k8s_servicedeployment",
  "classes": {
   "k8s-servicedeployment:index:ServiceDeployment": "ServiceDeployment"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "k8s-servicedeployment",
  "token": "pulumi:providers:k8s-servicedeployment",
  "fqn": "pulumi_k8s_servicedeployment",
  "class": "Provider"
 }
]
"""
)
